---
# tasks file for zsh role
# Removed hosts, become - handled by playbook

- name: Ensure Zsh is installed
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: yes

- name: Ensure Zsh is listed in /etc/shells
  lineinfile:
    path: /etc/shells
    line: /usr/bin/zsh
    state: present

- name: Get user home directory
  become: false
  shell: echo $HOME
  register: user_home
  changed_when: false

- name: Check if Oh My Zsh is installed
  become: false
  stat:
    path: "{{ user_home.stdout }}/.oh-my-zsh"
  register: oh_my_zsh_installed

- name: Install Oh My Zsh
  become: false
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ user_home.stdout }}/.oh-my-zsh"
  when: not oh_my_zsh_installed.stat.exists

- name: Set Zsh as the default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh

- name: Verify Zsh is set as default shell in /etc/passwd
  shell: "getent passwd {{ ansible_env.USER }} | cut -d: -f7"
  register: configured_shell
  changed_when: false
  failed_when: "'/usr/bin/zsh' not in configured_shell.stdout"

- name: Print the configured default shell
  debug:
    msg: "Configured default shell is {{ configured_shell.stdout }}"

- name: Print the current default shell
  debug:
    msg: "Default shell is {{ default_shell.stdout }}"

- name: Copy .zshrc template if it doesn't exist
  become: false
  ansible.builtin.copy:
    src: "{{ user_home.stdout }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ user_home.stdout }}/.zshrc"
    remote_src: yes
    force: no
  when: oh_my_zsh_installed.stat.exists

- name: Configure a custom theme for Oh My Zsh (optional)
  become: false
  ansible.builtin.lineinfile:
    path: "{{ user_home.stdout }}/.zshrc"
    regexp: '^ZSH_THEME="(.*)"'
    line: 'ZSH_THEME="agnoster"' # Example theme
    backrefs: yes
  when: oh_my_zsh_installed.stat.exists

- name: Reload Zsh configuration (optional)
  shell: source {{ user_home.stdout }}/.zshrc
  args:
    executable: /bin/zsh
